### PR TITLE
[Bugfix]: Fix the list plugin showing error in TYPO3 9

### PR DESCRIPTION
**Pull request by fawmi**
The TYPO3 9 plugin shows an error, when the plugin is added as content element. 
The error says "Invalid value [realty_pi1]"
The error disappears when I move the call to the `ExtensionManagementUtility::addPlugin` method to the tt_content file. 
This PR moves the call to  `ExtensionManagementUtility::addPlugin`  tt_content.php file.

### CODE REVIEW

**Comment by oliverklee** [comment]
Thanks for contributing this PR, @fawmi! I'll review it shortly.

**Review by oliverklee — CHANGES_REQUESTED** [review]
You're not moving things around. Instead, the patch removes some things (the hiding/showing of content element fields for flexforms) and duplicates other things (e.g., the BE module registration). Possible something got mixed up. Could you please check?

And could you please add a line to the changelog (newest on top)? Then I don't need to have another PR for this. Thanks!

**Comment by fawmi** [comment]
@oliverklee 
Sorry, wrong changes were committed. I fixed the changes and added a line in the changelogs file.

**Comment by fawmi** [comment]
@oliverklee 
Not related to this PR, but there are a few other changes for making this extension TYPO3 10 compatible, which I would like to open a PR for. 
Is it possible to create a typo3-10 Branch so that I can commit my changes there? 

And how is the support policy for the extension, should the version 3.3 (or whatever version it will be) support TYPO3 8 as well?

**Comment by oliverklee** [comment]
@fawmi I've moved your question to [the Discussions section](https://github.com/oliverklee/ext-realty/discussions/326) and replied there.

**Comment by oliverklee** [comment]
@fawmi I have no idea why the V9 tests are running on the CI for this branch. For starters, could you please check that your branch is based on the latest `main` branch?

**Comment by fawmi** [comment]
My branch is based on V9. Should i create a PR based on main?

**Comment by oliverklee** [comment]
> My branch is based on feature/typo3-9. Should i create a PR based on main?

Yes, please, always.

**Comment by oliverklee** [comment]
(You can also rebase and force-push in order to keep this PR.)

**Comment by oliverklee** [comment]
(The version 9 branch currently is only for seeing what breaks, not for building a 9-compatible version.)

**Comment by oliverklee** [comment]
Okay, thanks for checking and reporting back! Closing then.

**Pull request closed without merging**
