### PR TITLE
[TASK] Change locallang XML files to XLIFF and move to language folder

### PR DESCRIPTION
**Pull request by jokumer**
A start to modernize EXT:realty for TYPO3 7 and 8

### CODE REVIEW

**Comment by oliverklee** [comment]
Thanks for the PR! I'll review it.

**Comment by jokumer** [comment]
The wizard for new content elements is broken - can not handle xliff files.

**Comment by oliverklee** [comment]
@jokumer You'll need to update the wizard class like this:
https://github.com/oliverklee/ext-seminars/commit/fcdc26a146d5bf19c8ea13f8a9bba927479b7780#diff-4ac504515b5379074ed332e5993f7832

**Comment by jokumer** [comment]
Perfect hint, thx. I'll implement it

**Comment by oliverklee** [comment]
Merged. Thanks for contributing, @jokumer! :heart:

**Comment by jokumer** [comment]
And thank you for distributing this extension @oliverklee.

**Comment by oliverklee** [comment]
@jokumer By the way, I think the email address which you've used in the commit is not registered for your GitHub account, i.e., GitHub cannot connect the commit to your account. I propose you either add that email address to you GitHub account, or you change the `user.email` settings in your local Git installation. (And if you also could put your full name in  `user.name`, that would be perfect so the praise in the Git history really is on you.)

**Comment by jokumer** [comment]
@oliverklee should we update locallangfiles on translationserver too? https://translation.typo3.org/projects/TYPO3.ext.realty/

**Comment by oliverklee** [comment]
Maybe … honestly, I have no idea how the translation server works, what is automated and what extension authors need to do. Do you know more about this (or have good starting URLs for learning more)?

**Comment by oliverklee** [comment]
> It is a bit difficult at some points - but it works. I will do it. 

Thanks! :heart:

**Comment by jokumer** [comment]
It is first possible, if the new version has been uploaded to TER. Will have a look at it, after next published release.

**Comment by oliverklee** [comment]
Okay.

**Pull request closed without merging**
